<?php

$title = 'API Objects';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('crud', array('action'=>'add'));?>">Add new object</a>
</p>

<table class="table">
<tr>
    <th>Id</th>
    <th>Active</th>
    <th>Training</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($objects as $object) : ?>
<tr>
    <td><?php echo  $object['id'];?></td>
    <td><?php echo ($object['active'])   ? 'true' : 'false';?></td>
    <td><?php echo ($object['training']) ? 'true' : 'false';?></td>
    <td>
        <a href="<?php echo $this->url('crud',
            array('action'=>'edit', 'id' => $object['id']));?>">Edit</a>
        <a href="<?php echo $this->url('crud',
            array('action'=>'delete', 'id' => $object['id']));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>